hwdec=vulkan-copy
gpu-context=auto
gpu-api=auto

# language prefs
alang=ja,jp,jpn,japanese,en,eng,english,English,enUS,en-US,tr,tur,turkish,tr-TR
slang=en,eng,english,English,enUS,en-US,tr,tur,turkish,tr-TR,ja,jp,jpn,japanese

save-position-on-quit=yes

# subtitles
sub-auto=fuzzy
subs-with-matching-audio=yes
sub-file-paths=ass:srt:sub:subs:subtitles:subs.en:subs.ja
#sub-pos=98
sub-font="Noto Sans"
sub-bold=yes
sub-font-size=56
sub-border-size=3

# screenshots
screenshot-directory=~/Pictures
screenshot-template="%F_%wHh%wMm%wSs_%wTms"
screenshot-format=webp
screenshot-high-bit-depth=yes
