[General]
configversion=7.1
firstlaunch=true
optionstab=3

[options]
afterdelete=2
allowmimecontentdetection=false
askdelete=true
bgcolor=#212121
bgcolorenabled=true
colorspaceconversion=1
cropmode=0
cursorzoom=true
filteringenabled=true
fractionalzoom=false
fullscreendetails=false
language=system
loopfoldersenabled=true
maxwindowresizedpercentage=70
menubarenabled=false
minwindowresizedpercentage=20
pastactualsizeenabled=true
preloadingmode=1
quitonlastwindow=false
saverecents=false
scalefactor=25
scalingenabled=true
scalingtwoenabled=true
scrollzoom=1
skiphidden=true
slideshowreversed=0
slideshowtimer=5
sortdescending=0
sortmode=0
titlebaralwaysdark=true
titlebarmode=1
updatenotifications=false
windowresizemode=1

[recents]
recentFiles=@Invalid()

[shortcuts]
copy=Ctrl+C, Ctrl+Ins
decreasespeed=[
delete=Ctrl+Backspace, Del
deletepermanent=Shift+Del
firstfile=Home
flip=Ctrl+F
fullscreen=Ctrl+Shift+F
increasespeed=]
lastfile=End
mirror=F
nextfile=Right, PgUp
nextframe=N
open=Ctrl+O
opencontainingfolder=@Invalid()
openurl=Ctrl+Shift+O
options="Ctrl+Shift+,"
originalsize=O
paste=Ctrl+V, Shift+Ins
pause=P
previousfile=Left, PgDown
quit=Esc, Q
reloadfile=F5, Refresh
rename=Ctrl+Return, F2, Ctrl+R
resetspeed=\\
resetzoom=Ctrl+0
rotateleft=Down
rotateright=Up
saveframeas=Ctrl+S
showfileinfo=I
slideshow=@Invalid()
undo=Ctrl+Z
zoomin=Shift+PgUp
zoomout=Shift+PgDown
